import type { SiteDictionary } from "@/lib/i18n/types";

const tr: SiteDictionary = {
  meta: {
    title: "KITE Growth Agency — Tasarım Sistemi",
    description:
      "KITE Growth Agency için geliştirilen editoryal tasarım sisteminin dahili önizlemesi.",
  },
  brand: {
    name: "KITE",
    agencyType: "GROWTH AGENCY",
    statement: "We're the wind behind your brand.",
    location: "ISTANBUL & BALI BASED",
    globalNote: "WORKING GLOBALLY",
  },
  ui: {
    skipToContent: "İçeriğe geç",
    languageSwitcherLabel: "Dili değiştir",
    back: "Geri",
    closeLabel: "Kapat",
  },
  header: {
    locationShort: "ISTANBUL & BALI",
    nav: {
      work: "İŞLER",
      services: "HİZMETLER",
      about: "HAKKIMIZDA",
      thinking: "THINKING",
      contact: "İLETİŞİM",
    },
    cta: "PROJE BAŞLAT",
    mobileMenu: {
      openLabel: "Menü",
      closeLabel: "Kapat",
      ariaLabel: "Ana menü",
      menuEyebrow: "MENÜ",
      nav: {
        work: "İŞLER",
        services: "HİZMETLER",
        about: "HAKKIMIZDA",
        thinking: "THINKING",
        contact: "İLETİŞİM",
      },
      social: {
        instagram: "Instagram",
        linkedin: "LinkedIn",
        behance: "Behance",
        email: "E-posta",
      },
    },
  },
  hero: {
    indexLabel: "HERO",
    headline: [
      [{ text: "İYİ MARKALARIN" }],
      [{ text: "FAZLA GÜRÜLTÜYE" }],
      [{ text: "İHTİYACI YOK." }],
    ],
    secondaryStatement: [{ text: "GEREKEN TEK" }, { text: "ŞEY" }, { text: "YÖN.", accent: true }],
    supportingCopy: [
      "Hareket eden, bağ kuran ve büyüyen markalar inşa eden kreatif bir growth ajansıyız.",
      "—",
      "Strateji. Kreatiflik. Teknoloji. Büyüme.",
    ],
    primaryCta: "PROJENİ KONUŞALIM",
    secondaryCta: "İŞLERİMİZİ GÖR",
    capabilities: ["CREATIVE", "MEDIA", "WEB", "AI", "CRM"],
    showreelLabel: "SHOWREEL İZLE",
    scrollLabel: "KEŞFETMEK İÇİN KAYDIR",
    stampLines: ["MARKALARI", "İLERİ TAŞI"],
    nextSectionHint: {
      number: "002",
      title: "SEÇİLİ İŞLER",
      viewAllLabel: "TÜM PROJELERİ GÖR",
    },
  },
  work: {
    indexLabel: "SEÇİLİ İŞLER",
    supportingLines: ["FARKLI SEKTÖRLER.", "AYNI MESELE:", "DOĞRU YÖN."],
    featuredLabel: "ÖNE ÇIKAN",
    statusOngoing: "DEVAM EDİYOR",
    nextSectionHint: {
      number: "003",
      title: "NELER YAPIYORUZ",
    },
    projects: [
      {
        number: "01",
        name: "DESETOUR",
        services: ["Website", "Reklam", "Sosyal Medya", "CRM"],
      },
      {
        number: "02",
        name: "ECRU ATELIER",
        services: ["Reklam", "Sosyal Medya"],
      },
      {
        number: "03",
        name: "TITOCAR",
        services: ["Reklam Yönetimi"],
      },
      {
        number: "04",
        name: "LYXASKIN",
        services: ["Sosyal Medya", "Reklam"],
      },
      {
        number: "05",
        name: "PETCANVAS",
        services: ["Reklam Yönetimi"],
      },
    ],
    cta: {
      number: "06",
      headline: "BİR MARKA EKSİK.",
      label: "TANIŞALIM.",
    },
  },
  capabilities: {
    indexLabel: "NELER YAPIYORUZ",
    introStatement: "Büyümeyi tek bir hizmet olarak görmüyoruz.",
    introSupport:
      "Markanın ne söylediğinden reklamın kime ulaştığına, kullanıcının hangi sayfaya indiğinden sonrasında CRM'de ne olduğuna kadar bütün yolculuğu birlikte ele alıyoruz.",
    systemLine: ["STRATEGY", "CREATIVE", "MEDIA", "WEB", "DATA", "CRM"],
    items: [
      {
        number: "01",
        title: "STRATEJİ & GROWTH",
        statement: [
          { text: "Ne söyleyeceğimizi, kime söyleyeceğimizi ve hangi noktada " },
          { text: "neyi test edeceğimizi", accent: true },
          { text: " belirliyoruz." },
        ],
        groups: [
          {
            items: [
              "Growth Audit",
              "Pazar ve Rakip Analizi",
              "Audience Research",
              "Positioning",
              "Messaging",
              "Offer Strategy",
              "Campaign Planning",
              "Channel Strategy",
              "Testing Roadmap",
            ],
          },
        ],
        secondary: {
          label: "ORTAYA ÇIKANLAR",
          items: ["Growth Roadmap", "Campaign Architecture", "Messaging Framework", "Test Planı", "Channel Planı"],
        },
      },
      {
        number: "02",
        title: "PERFORMANCE MEDIA",
        statement: [
          { text: "Bütçeyi harcamak değil, " },
          { text: "doğru yere", accent: true },
          { text: " yönlendirmek." },
        ],
        supportingCopy: "Her kampanyayı tek başına değil, funnel'ın bir parçası olarak değerlendiriyoruz.",
        groups: [
          {
            items: [
              "Meta Ads",
              "Google Ads",
              "TikTok Ads",
              "YouTube",
              "Search",
              "Performance Max",
              "Retargeting",
              "Lookalike Audiences",
              "Audience Testing",
              "Creative Testing",
              "Budget Optimisation",
              "Campaign Scaling",
            ],
          },
        ],
        secondary: {
          label: "ÖLÇTÜĞÜMÜZ NOKTALAR",
          items: ["CPA", "CAC", "ROAS", "CTR", "Conversion Rate", "Creative Performance", "Audience Saturation"],
        },
      },
      {
        number: "03",
        title: "CREATIVE & CONTENT",
        statement: [
          { text: "İyi creative sadece güzel görünmez. " },
          { text: "Bir şey yaptırır.", accent: true },
        ],
        groups: [
          {
            label: "BRAND CONTENT",
            items: [
              "Social Content",
              "Campaign Concepts",
              "Editorial Content",
              "Product Storytelling",
              "Reels",
              "Short Form Video",
              "Motion Design",
            ],
          },
          {
            label: "PERFORMANCE CREATIVE",
            items: [
              "Static Ads",
              "Motion Ads",
              "Video Ads",
              "Creative Variations",
              "Multiple Hooks",
              "Multiple Angles",
              "Retargeting Creative",
              "UGC Concepts",
            ],
          },
        ],
        secondary: {
          label: "AI DESTEKLİ ÜRETİM",
          items: ["AI Imagery", "AI Video", "Rapid Prototyping", "Creative Variation", "Concept Development"],
          note: "AI üretim kapasitesini büyütür. Kararı hâlâ fikir verir.",
        },
      },
      {
        number: "04",
        title: "WEB & CONVERSION",
        statement: [
          { text: "Tıklamadan sonrası da " },
          { text: "reklamın bir parçası.", accent: true },
        ],
        supportingCopy: "Reklamın getirdiği ilgiyi, tasarlanmış bir kullanıcı yolculuğu ile dönüşüme çeviriyoruz.",
        groups: [
          {
            items: [
              "Website",
              "Landing Page",
              "E-Commerce",
              "Campaign Page",
              "Product Page",
              "UX Architecture",
              "Conversion Copy",
              "CTA Hierarchy",
              "Lead Forms",
              "Checkout Flow",
              "CRO",
              "A/B Testing",
              "Responsive Design",
            ],
          },
        ],
      },
      {
        number: "05",
        title: "DATA, CRM & LIFECYCLE",
        statement: [
          { text: "Tıklamanın sonrasında ne olduğunu göremiyorsak, öncesini " },
          { text: "sağlıklı şekilde büyütemeyiz.", accent: true },
        ],
        groups: [
          { label: "MEASUREMENT", items: ["GA4", "Google Tag Manager", "Meta Pixel", "Conversions API", "Event Tracking"] },
          { label: "CRM", items: ["CRM Setup", "Lead Routing", "Customer Segmentation", "CRM Integrations"] },
          { label: "LIFECYCLE", items: ["Email Flows", "Retargeting Audiences", "Lead Nurturing", "Customer Reactivation"] },
          {
            label: "REPORTING",
            items: ["Performance Dashboards", "Channel Reporting", "Funnel Visibility", "Campaign Learning"],
          },
        ],
      },
    ],
  },
  investigation: {
    folioNumber: "004",
    title: "SORUŞTURMA",
    introLines: ["BİR MARKAYLA KARŞI KARŞIYA GELDİĞİMİZDE,", "ÖNCE ŞU 13 SORUYU SORARIZ."],
    investigationDetails: ["DURUM: İNCELENİYOR", "KANIT: DATA", "NOT: HİS YETERLİ DEĞİL"],
    questions: [
      {
        number: "01",
        question: "KİM?",
        answerLines: [[{ text: "Marka kim?" }], [{ text: "Gerçekten kim?" }]],
        label: "BRAND / POSITIONING",
      },
      {
        number: "02",
        question: "KİME?",
        answerLines: [
          [{ text: "Kime konuşuyoruz?" }],
          [{ text: "'Herkese'", accent: true }, { text: " cevap sayılmıyor." }],
        ],
        label: "AUDIENCE",
      },
      {
        number: "03",
        question: "NEYİ?",
        answerLines: [[{ text: "Aslında ne satıyoruz?" }], [{ text: "Ürünü mü, fikri mi?" }]],
        label: "OFFER",
      },
      {
        number: "04",
        question: "NİYE?",
        answerLines: [
          [{ text: "Niye senden alsın?" }],
          [{ text: "'Kaliteliyiz'", accent: true }, { text: " cevap sayılmıyor." }],
        ],
        label: "VALUE PROPOSITION",
      },
      {
        number: "05",
        question: "NEREDE?",
        answerLines: [[{ text: "Nerede karşısına çıkıyoruz?" }], [{ text: "Her yerde olmak strateji değil." }]],
        label: "CHANNEL",
      },
      {
        number: "06",
        question: "NEYLE?",
        answerLines: [
          [{ text: "Hangi creative ile?" }],
          [{ text: "Güzel olanla değil, " }, { text: "çalışanla.", accent: true }],
        ],
        label: "CREATIVE",
      },
      {
        number: "07",
        question: "NE ZAMAN?",
        answerLines: [[{ text: "Ne zaman karşısına çıkıyoruz?" }], [{ text: "Sürekli çıkmak cevap değil." }]],
        label: "TIMING / FREQUENCY",
      },
      {
        number: "08",
        question: "KAÇA?",
        answerLines: [
          [{ text: "Bir müşteriyi kaça getiriyoruz?" }],
          [{ text: "'Bütçe gidiyor'", accent: true }, { text: " metrik değil." }],
        ],
        label: "CAC / CPA",
      },
      {
        number: "09",
        question: "NEREYE?",
        answerLines: [[{ text: "Tıklayınca nereye gidiyor?" }], [{ text: "Ve orada neden kalıyor?" }]],
        label: "LANDING / CONVERSION",
      },
      {
        number: "10",
        question: "NERDE KOPTU?",
        answerLines: [[{ text: "Nerede vazgeçiyor?" }], [{ text: "Bir yerde kesin kopuyor." }]],
        label: "FUNNEL",
      },
      {
        number: "11",
        question: "KİM DÖNDÜ?",
        answerLines: [[{ text: "Kim geri geldi?" }], [{ text: "İlk satış dosyayı kapatmıyor." }]],
        label: "RETENTION / CRM",
      },
      {
        number: "12",
        question: "NE TUTTU?",
        answerLines: [[{ text: "Gerçekte ne çalıştı?" }], [{ text: "Hissettiğimiz değil.", accent: true }]],
        label: "PERFORMANCE / DATA",
      },
      {
        number: "13",
        question: "ŞİMDİ NE?",
        answerLines: [
          [{ text: "Sırada neyi değiştiriyoruz?" }],
          [{ text: "'Biraz daha bütçe'", accent: true }, { text: " tek cevap değil." }],
        ],
        label: "OPTIMISATION",
      },
    ],
    ending: [{ text: "13 sorudan 4'üne cevap verebiliyorsak," }, { text: "işin yarısı tamam.", accent: true }],
    endingNote: "Geri kalanı data halleder.",
  },
  diagnosis: {
    folioNumber: "005",
    title: "TEŞHİS",
    introLines: ["MARKALAR BİZE GENELDE", "ŞU ALTI CÜMLEDEN BİRİYLE GELİYOR."],
    introSupport:
      "Performans düştüğünde ilk refleks çoğu zaman reklamı değiştirmek oluyor. Oysa sorun creative'den website'e, offer'dan tracking'e kadar yolculuğun başka bir yerinde olabilir.",
    problems: [
      {
        number: "01",
        label: "BELİRTİ",
        statement: [[{ text: "Daha fazla harcıyoruz." }], [{ text: "Sonuç aynı.", accent: true }]],
        secondaryLine: "Bütçe artınca sorun çözülmüyorsa, sorun bütçe olmayabilir.",
        causes: ["Creative Fatigue", "Audience Saturation", "Offer", "Landing Page", "Tracking", "Campaign Structure"],
        conclusion: [[{ text: "Biz sadece Ads Manager'a bakmıyoruz." }]],
      },
      {
        number: "02",
        statement: [[{ text: "İçerikler güzel." }], [{ text: "Ama satmıyor.", accent: true }]],
        secondaryLine: "Güzel görünmek başka, kullanıcıyı bir sonraki adıma taşımak başka.",
        causes: ["Weak Hook", "Wrong Message", "No Clear CTA", "Format", "Creative Fatigue", "Offer Mismatch"],
        stages: ["Dikkat", "İlgi", "Aksiyon"],
        conclusion: [[{ text: "Güzel post, tek başına iş modeli değil." }]],
      },
      {
        number: "03",
        label: "KAYIP NOKTASI",
        statement: [[{ text: "Trafik var." }], [{ text: "Dönüşüm yok.", accent: true }]],
        secondaryLine: "Tıklama var. Sonrası kayıp.",
        causes: ["Landing Page", "Mobile UX", "Page Speed", "CTA", "Form Friction", "Checkout", "Conversion Copy"],
        conclusion: [[{ text: "Trafik var ama yolculuk çalışmıyor olabilir." }]],
      },
      {
        number: "04",
        statement: [[{ text: "Her kanalda" }], [{ text: "başka bir markayız.", accent: true }]],
        secondaryLine: "Instagram başka şey söylüyor. Google başka. Website başka. Sales ekibi başka.",
        causes: [
          "Positioning",
          "Messaging",
          "Offer Hierarchy",
          "Campaign Messaging",
          "Content Direction",
          "Sales Narrative",
        ],
        conclusion: [
          [{ text: "İyi bir marka her yerde aynı cümleyi tekrar etmez." }],
          [{ text: "Aynı fikri taşır.", accent: true }],
        ],
      },
      {
        number: "05",
        label: "SİNYAL",
        statement: [[{ text: "Data çok." }], [{ text: "Cevap yok.", accent: true }]],
        secondaryLine: "Dört dashboard açık. Hâlâ ne yapacağımız belli değil.",
        causes: ["Meta", "Google", "GA4", "CRM", "Website", "E Commerce"],
        diagnosticQuestions: [
          "Ne çalışıyor?",
          "Neden çalışıyor?",
          "Nerede kayıp var?",
          "Sırada neyi değiştireceğiz?",
        ],
        conclusion: [
          [{ text: "Dashboard cevap değil." }],
          [{ text: "Karar çıkaramıyorsak data sadece kalabalık." }],
        ],
      },
      {
        number: "06",
        statement: [[{ text: "Her şey yapılıyor." }], [{ text: "Hiçbir şey birbirine bağlı değil." }]],
        supportingLines: ["Reklam var.", "Sosyal medya var.", "Website var.", "CRM var.", "Birbirlerinden haberleri yok."],
        systemLine: ["Creative", "Media", "Web", "Data", "CRM"],
        conclusion: [[{ text: "Kite tam olarak bu parçaların arasına giriyor." }]],
      },
    ],
  },
  system: {
    folioNumber: "006",
    title: "SİSTEM",
    introLines: ["BÜYÜME", "TEK BİR KANALDA", "GERÇEKLEŞMEZ."],
    introSupport:
      "Creative, media, web, data ve CRM birbirinden bağımsız çalıştığında büyümenin nerede başladığını, nerede kaybolduğunu görmek zorlaşır. Biz bu parçaları aynı sistem içinde çalıştırıyoruz.",
    canvasDetails: ["SYSTEM / 01–06", "LOOP: CONTINUOUS"],
    stages: [
      {
        number: "01",
        name: "ANLA",
        term: "INSIGHT",
        question: "Ne oluyor?",
        details: ["Pazar", "Audience", "Rakipler", "Geçmiş performans", "Customer journey", "Mevcut data"],
        outcome: "Önce tabloyu görüyoruz.",
      },
      {
        number: "02",
        name: "KONUMLANDIR",
        term: "DIRECTION",
        question: "Ne söyleyeceğiz?",
        details: ["Positioning", "Offer", "Messaging", "Campaign angle", "Channel role", "Testing priorities"],
        outcome: "Yönü belirliyoruz.",
      },
      {
        number: "03",
        name: "ÜRET",
        term: "CREATIVE",
        question: "İnsan neden durup baksın?",
        details: ["Campaign concept", "Static creative", "Video", "Content", "Hooks", "Angles", "Variations"],
        outcome: "Fikri görünür hale getiriyoruz.",
      },
      {
        number: "04",
        name: "DAĞIT",
        term: "MEDIA",
        question: "Kime, nerede, ne kadar?",
        details: ["Meta", "Google", "TikTok", "YouTube", "Prospecting", "Retargeting", "Budget allocation"],
        outcome: "Doğru mesajı doğru yere taşıyoruz.",
      },
      {
        number: "05",
        name: "DÖNÜŞTÜR",
        term: "CONVERSION",
        question: "Tıkladı. Şimdi?",
        details: ["Website", "Landing Page", "E Commerce", "Form", "Checkout", "CRM", "Lead flow"],
        outcome: "İlgiyi aksiyona çeviriyoruz.",
      },
      {
        number: "06",
        name: "ÖĞREN",
        term: "DATA",
        question: "Peki ne oldu?",
        details: ["Campaign data", "Creative data", "Website behaviour", "Conversion data", "CRM", "Customer quality"],
        outcome: "Sonucu yeni karara çeviriyoruz.",
      },
    ],
    loopNote: "01'e döner.",
    closing: [
      { text: "Her kampanya," },
      { text: "bir sonrakine" },
      { text: "bir şey öğretmeli.", accent: true },
    ],
    closingNote: "Yoksa yalnızca aynı şeyi tekrar etmiş oluruz.",
  },
  firstMonth: {
    folioNumber: "007",
    title: "İLK 30 GÜN",
    introLines: [
      [{ text: "İlk işimiz" }],
      [{ text: "bir şey üretmek değil." }],
      [{ text: "Neyi değiştirmemiz", accent: true }],
      [{ text: "gerektiğini anlamak." }],
    ],
    introSupport:
      "Yeni bir creative, kampanya veya landing page bazen gerçekten gereklidir. Bazen de değildir. İlk günlerde amacımız daha fazla şey yapmak değil, doğru şeyi bulmaktır.",
    phases: [
      {
        number: "01",
        timeLabel: "GÜN 01–07",
        title: "Büyük resmi çıkarıyoruz.",
        statement:
          "Önce mevcut düzene bakıyoruz. Çünkü neyin çalıştığını bilmeden neyi değiştireceğimize karar veremeyiz.",
        areasLabel: "NELERE BAKIYORUZ",
        areas: [
          "Business Goals",
          "Existing Campaigns",
          "Creative Library",
          "Website",
          "Landing Pages",
          "Analytics",
          "CRM",
          "Tracking",
          "Competitors",
          "Customer Journey",
          "Historical Performance",
        ],
        outputLabel: "İLK ÇIKTI",
        output: "Mevcut durum analizi",
        note: "Ne var, ne yok, ne çalışıyor, ne sadece orada duruyor?",
        microLabel: "STATUS: ANALİZ",
      },
      {
        number: "02",
        timeLabel: "GÜN 08–14",
        title: "Kaybın nerede olduğunu buluyoruz.",
        statement:
          "Problem reklam hesabında mı, creative'de mi, offer'da mı, conversion'da mı? Önce bunu ayırıyoruz.",
        areasLabel: "TEŞHİS ALANLARI",
        areas: ["Acquisition", "Creative", "Audience", "Offer", "Conversion", "Tracking", "Messaging", "Retention"],
        outputLabel: "ÇIKTI",
        output: "Önceliklendirilmiş growth roadmap",
        note: "Her problem aynı anda çözülmez. Önce en çok hareket yaratacak yere dokunuruz.",
      },
      {
        number: "03",
        timeLabel: "GÜN 15–30",
        title: "Sistemi kuruyoruz.",
        statement: "Teşhis netleştiğinde gerekli parçaları üretmeye ve birbirine bağlamaya başlıyoruz.",
        areasLabel: "OLASI İŞ AKIŞLARI",
        areas: [
          "Campaign Structure",
          "Creative Production",
          "Landing Page",
          "Tracking",
          "Audience Structure",
          "CRM",
          "Reporting",
          "Conversion Flow",
          "Testing Infrastructure",
        ],
        outputLabel: "ÇIKTI",
        output: "Launch ready yapı",
        note: "Yeni bir sistem gerekiyorsa kuruyoruz. Gerekmiyorsa sırf yeni görünsün diye yeniden yapmıyoruz.",
      },
      {
        number: "04",
        timeLabel: "30. GÜNDEN SONRA",
        title: "Döngü başlıyor.",
        statement: "Bundan sonrası tekrar eden bir üretim takvimi değil. Öğrenme döngüsü.",
        loopSequence: ["DATA", "HİPOTEZ", "CREATIVE", "TEST", "SONUÇ", "YENİ KARAR"],
        questions: ["NE ÇALIŞTI?", "NE ÇALIŞMADI?", "NEDEN?", "SIRADA NEYİ TEST EDİYORUZ?"],
        microLabel: "SIGNAL",
      },
    ],
    closing: [
      { text: "Aynı şeyi her ay" },
      { text: "tekrar etmiyoruz." },
      { text: "Her ay bir öncekinden" },
      { text: "daha fazla şey biliyoruz.", accent: true },
    ],
  },
  caseStudies: {
    folioNumber: "008",
    title: "İŞİN ARKASINDAKİ İŞ",
    introLines: [
      [{ text: "Güzel görünen işi" }],
      [{ text: "göstermek kolay." }],
      [{ text: "Asıl mesele," }],
      [{ text: "arkasında ne kurduğun.", accent: true }],
    ],
    introSupport:
      "Bazı projelerde creative'e dokunuyoruz. Bazılarında media'ya. Bazılarında ise website'ten CRM'e kadar bütün yolculuğa. Burada işin görünen tarafından çok, arkasındaki sistemi gösteriyoruz.",
    scopeLabel: "KAPSAM",
    contextLabel: "BAĞLAM",
    workLabel: "KITE NEYE DOKUNDU?",
    systemLabel: "SİSTEM",
    ongoingLabel: "DEVAM EDİYOR",
    cases: [
      {
        number: "01",
        client: "DESETOUR",
        category: "TRAVEL / EXPERIENCES",
        statement: [{ text: "Bir tur sitesi değil." }, { text: "Bütün bir digital journey.", accent: true }],
        context:
          "DeseTour, İstanbul'a özel kürasyonlu deneyimler kuruyor. Kite'nin rolü tek bir pazarlama kanalından çok, müşteri yolculuğunun birden fazla noktasına yayılıyor.",
        scope: ["Website", "Paid Media", "Social Media", "CRM Systems"],
        workItems: [
          "Digital experience",
          "Tour presentation",
          "Booking journey",
          "Paid media infrastructure",
          "Social content system",
          "Lead capture",
          "CRM flow",
        ],
        systemSequence: ["CONTENT / ADS", "WEBSITE", "BOOKING", "CRM"],
        systemJoiner: "arrow",
        smallLine: [{ text: "Reklamdan booking'e." }, { text: "Booking'den CRM'e." }],
        imageAlign: "left",
      },
      {
        number: "02",
        client: "ECRU ATELIER",
        category: "JEWELRY / E COMMERCE",
        statement: [{ text: "Premium görünmek yetmez." }, { text: "Creative çalışmak zorunda.", accent: true }],
        context:
          "Ecru Atelier premium bir mücevher markası. Bu çalışma, marka tutarlılığını paid social'ın sürekli creative ihtiyacıyla birleştiriyor.",
        scope: ["Social Media Management", "Creative", "Paid Media"],
        workItems: [
          "Social content",
          "Campaign communication",
          "Product storytelling",
          "Performance creative",
          "Creative variations",
          "Meta advertising",
          "Campaign optimisation",
        ],
        systemSequence: ["BRAND", "CREATIVE", "MEDIA"],
        systemJoiner: "plus",
        smallLine: [{ text: "Brand ile performance" }, { text: "aynı creative'de buluşuyor.", accent: true }],
        dark: true,
        imageAlign: "right",
      },
      {
        number: "03",
        client: "LYXASKIN",
        category: "SKINCARE",
        statement: [{ text: "Content üretiyoruz." }, { text: "Sonra ne yaptığına bakıyoruz.", accent: true }],
        context: "Lyxa Skin, devam eden bir sosyal medya ve performans ortaklığı.",
        scope: ["Social Media Management", "Creative", "Paid Media"],
        workItems: [
          "Product communication",
          "Social content",
          "Creative direction",
          "Performance creative",
          "Paid campaigns",
          "Creative iteration",
        ],
        systemSequence: ["ÜRET", "YAYINLA", "ÖLÇ", "ÖĞREN", "YENİDEN ÜRET"],
        systemJoiner: "arrow",
        systemLoop: true,
        closingLine: [{ text: "Creative bir teslim değil." }, { text: "Döngü.", accent: true }],
        ongoing: true,
        imageAlign: "left",
      },
    ],
    closing: [
      { text: "Her işin kapsamı farklı." },
      { text: "Mantığı aynı.", accent: true },
      { text: "Problemi bul." },
      { text: "Doğru parçaları bağla." },
      { text: "Öğren." },
    ],
  },
  collaboration: {
    folioNumber: "009",
    title: "BİZİMLE NASIL ÇALIŞABİLİRSİNİZ?",
    introLines: [
      [{ text: "Her markanın" }],
      [{ text: "ihtiyacı aynı değil." }],
      [{ text: "Çalışma biçimi de" }],
      [{ text: "aynı olmak zorunda değil." }],
    ],
    introSupport:
      "Bazen markanın dışarıdaki growth ekibi gibi çalışıyoruz. Bazen yalnızca creative sistemi kuruyoruz. Bazen de tek bir launch ya da digital build için devreye giriyoruz.",
    priorityLabel: "EN KAPSAMLI MODEL",
    bestForLabel: "KİM İÇİN?",
    scopeLabel: "KAPSAM",
    workingModelLabel: "ÇALIŞMA MODELİ",
    models: [
      {
        number: "01",
        title: "GROWTH PARTNERSHIP",
        description: "Markanın dışarıdaki growth ekibi gibi çalışıyoruz.",
        bestFor: [
          "Aktif reklam yatırımı olan",
          "Sürekli acquisition yapan",
          "Creative ihtiyacı devam eden",
          "Performance tarafını düzenli optimize etmek isteyen markalar",
        ],
        scope: ["Strategy", "Paid Media", "Creative", "Analytics", "CRO", "Landing Page", "Reporting", "Testing"],
        workingModel: "ONGOING RETAINER",
        smallLine: [{ text: "Bir kampanya değil." }, { text: "Sürekli çalışan bir sistem.", accent: true }],
        priority: true,
      },
      {
        number: "02",
        title: "CREATIVE PERFORMANCE",
        description:
          "Media çalışıyor ama creative tarafı yetişmiyorsa, sorun bütçeden önce üretim sisteminde olabilir.",
        bestFor: [
          "Kendi media ekibi olan",
          "Meta / TikTok tarafında aktif reklam veren",
          "Creative fatigue yaşayan",
          "Daha fazla varyasyon ve test ihtiyacı olan markalar",
        ],
        scope: [
          "Creative Strategy",
          "Static Ads",
          "Motion",
          "Video",
          "Hooks",
          "Angles",
          "Creative Variations",
          "Testing Plan",
          "Performance Learning",
        ],
        workingModel: "ONGOING / PERIODIC",
        smallLine: [{ text: "Daha fazla creative değil." }, { text: "Daha fazla öğrenen creative.", accent: true }],
        dark: true,
      },
      {
        number: "03",
        title: "DIGITAL BUILD",
        description: "Yeni bir digital experience gerekiyorsa, gerekli altyapıyı tek proje içinde kuruyoruz.",
        bestFor: [
          "Yeni website",
          "Landing page",
          "E Commerce",
          "CRM",
          "Analytics",
          "Tracking",
          "Conversion altyapısı ihtiyacı olan markalar",
        ],
        scope: [
          "Website",
          "Landing Page",
          "E Commerce",
          "UX",
          "Conversion Copy",
          "GA4",
          "GTM",
          "Pixel / CAPI",
          "CRM Setup",
          "Lead Flow",
        ],
        workingModel: "PROJECT BASED",
        smallLine: [{ text: "Yeni görünmek için değil." }, { text: "Daha iyi çalışmak için.", accent: true }],
      },
      {
        number: "04",
        title: "LAUNCH",
        description:
          "Yeni bir marka, ürün ya da pazar için kısa sürede aynı yönde hareket etmesi gereken parçaları bir araya getiriyoruz.",
        bestFor: ["Yeni marka", "Yeni ürün", "Yeni hizmet", "Yeni pazar", "Yeni kampanya dönemi"],
        scope: ["Strategy", "Positioning", "Messaging", "Creative", "Landing Page", "Paid Launch", "Tracking", "Reporting"],
        workingModel: "SPRINT / PROJECT",
        smallLine: [{ text: "Yayına çıkmak kolay." }, { text: "Hazır çıkmak daha zor.", accent: true }],
      },
    ],
    ctaHeadline: [
      { text: "Hangi modelin uyduğundan" },
      { text: "emin değilseniz," },
      { text: "sorun değil.", accent: true },
    ],
    ctaSupport: "İhtiyacı anlatın. Nereden başlamamız gerektiğini birlikte belirleyelim.",
    ctaLabel: "PROJENİ ANLAT",
  },
  principles: {
    folioNumber: "010",
    title: "BAZI ŞEYLERE İNANIYORUZ",
    introLines: ["BAZI ŞEYLERİ", "YAPMADAN ÖNCE,", "ONLAR HAKKINDA", "BİR FİKRİMİZ VAR."],
    introSupport:
      "Creative'den media'ya, website'ten data'ya kadar yaptığımız işlerin arkasında birkaç basit prensip var.",
    items: [
      {
        number: "01",
        statement: [
          [{ text: "Creative," }],
          [{ text: "reklamın süsü değildir." }],
          [{ text: "Performansın kendisidir.", accent: true }],
        ],
        supportingCopy:
          "Media ne kadar iyi yönetilirse yönetilsin, kimsenin durup bakmadığı bir creative'i ölçekleyemez.",
        technicalLabel: "CREATIVE / PERFORMANCE",
        variant: "C",
        dark: true,
      },
      {
        number: "02",
        statement: [[{ text: "Daha fazla trafik," }], [{ text: "kötü bir yolculuğu" }], [{ text: "kurtarmaz." }]],
        supportingCopy:
          "Reklam tıklamayı getirir. Website, landing page, offer ve conversion deneyimi sonrasını belirler.",
        technicalLabel: "TRAFFIC / CONVERSION",
        tinyLine: ["Tıklama başarı değil. Başlangıç."],
        variant: "A",
      },
      {
        number: "03",
        statement: [[{ text: "Ölçemediğimiz şeyi" }], [{ text: "sağlıklı şekilde" }], [{ text: "büyütemeyiz." }]],
        supportingCopy: "Data'nın amacı dashboard doldurmak değil, bir sonraki kararı daha iyi vermektir.",
        technicalLabel: "DATA / DECISION",
        tinyLine: ["Rakam çok olabilir.", "Cevap hâlâ az olabilir."],
        variant: "B",
      },
      {
        number: "04",
        statement: [
          [{ text: "AI daha fazla" }],
          [{ text: "üretmemizi sağlamalı." }],
          [{ text: "Daha vasat üretmemizi değil.", accent: true }],
        ],
        supportingCopy:
          "AI, fikir üretme, variation ve production kapasitesini büyütür. Ne kadarının yayına çıkacağına hâlâ creative judgement karar verir.",
        technicalLabel: "AI / PRODUCTION",
        variant: "C",
        dark: true,
      },
      {
        number: "05",
        statement: [[{ text: "Her kampanya," }], [{ text: "bir sonrakine" }], [{ text: "bir şey öğretmeli." }]],
        supportingCopy:
          "Test ettik, sonuç aldık ve aynı şeyi tekrar ettik diyorsak öğrenme döngüsünün yarısını kaçırmışızdır.",
        technicalLabel: "TEST / LEARN / ITERATE",
        tinyLine: ["Ne oldu?", "Neden oldu?", "Şimdi neyi değiştiriyoruz?"],
        variant: "A",
      },
      {
        number: "06",
        statement: [[{ text: "Brand ve performance" }], [{ text: "birbirinin rakibi değil." }]],
        supportingCopy:
          "Markayı korumak ile sonuç almak arasında seçim yapmak zorunda değiliz. İyi creative ikisini aynı anda taşıyabilir.",
        technicalLabel: "BRAND / PERFORMANCE",
        variant: "B",
      },
      {
        number: "07",
        statement: [[{ text: "Daha fazla kanal," }], [{ text: "her zaman daha fazla" }], [{ text: "büyüme değil." }]],
        supportingCopy: "Her yerde olmak yerine, hangi kanalın ne işe yaradığını bilmek daha değerlidir.",
        technicalLabel: "CHANNEL / FOCUS",
        tinyLine: ["Dağılmak da bir medya planıdır.", "Sadece iyi bir plan değildir."],
        variant: "A",
      },
      {
        number: "08",
        statement: [[{ text: "Her şeyi yeniden" }], [{ text: "yapmak zorunda değiliz." }]],
        supportingCopy:
          "Bazen problem sistemin tamamında değil, tek bir bağlantı noktasındadır. Çalışanı koruyup çalışmayanı değiştirmek de stratejidir.",
        technicalLabel: "DIAGNOSE / PRIORITISE",
        tinyLine: ["Yeni olan, her zaman daha iyi değildir."],
        variant: "B",
      },
    ],
    closing: [
      [{ text: "Bizim için growth," }],
      [{ text: "daha fazla şey yapmak değil." }],
      [{ text: "Doğru şeylerin" }],
      [{ text: "Birbiriyle " }, { text: "daha iyi", accent: true }],
      [{ text: "Çalışmasını", accent: true }, { text: " sağlamak." }],
    ],
  },
  measurement: {
    folioNumber: "011",
    title: "NEYE BAKIYORUZ?",
    introLines: ["TEK BİR METRİK,", "HİKÂYENİN TAMAMINI", "ANLATMAZ."],
    introSupport:
      "ROAS düşebilir çünkü creative yorulmuştur. Conversion düşebilir çünkü landing page çalışmıyordur. CAC yükselmiş olabilir ama gelen müşterinin kalitesi artmış olabilir. Bu yüzden rakamlara tek tek değil, birbirleriyle olan ilişkilerine bakıyoruz.",
    layers: [
      {
        number: "01",
        name: "MEDIA",
        mainQuestion: ["Doğru kişiye", "ulaşıyor muyuz?"],
        signals: ["CPM", "CTR", "CPC", "Frequency", "Reach", "Audience Saturation", "Spend Distribution"],
        meaning: "Dağıtımın maliyetini ve mesajın ilk temas performansını.",
        diagnosticQuestions: [
          "CTR düşüyor mu?",
          "Frequency yükseliyor mu?",
          "Audience yoruldu mu?",
          "Bütçe doğru kampanyaya gidiyor mu?",
        ],
        smallLine: [{ text: "Pahalı trafik her zaman" }, { text: "kötü trafik değildir." }],
        variant: "grid",
      },
      {
        number: "02",
        name: "CREATIVE",
        mainQuestion: ["İnsan neden", "durup bakıyor?"],
        signals: [
          "Hook Rate",
          "Hold Rate",
          "CTR",
          "Creative Fatigue",
          "Winning Angles",
          "Format Performance",
          "Message Performance",
        ],
        meaning: "Hangi fikirlerin dikkat çektiğini ve hangilerinin artık çalışmadığını.",
        diagnosticQuestions: ["Hangi hook tuttu?", "Hangi angle çalıştı?", "Video mu static mi?", "Ne zaman creative yoruldu?"],
        smallLine: [{ text: "Creative'in güzel olduğunu biz değil," }, { text: "davranış söyler.", accent: true }],
        variant: "typographic",
      },
      {
        number: "03",
        name: "WEBSITE",
        mainQuestion: ["Tıkladı.", "Peki sonra?"],
        signals: [
          "Engagement",
          "Bounce",
          "Scroll Depth",
          "Page Speed",
          "CTA Interaction",
          "Form Start",
          "Product View",
          "Checkout Behaviour",
        ],
        meaning: "Reklamdan gelen ilginin sayfa üzerinde nereye dönüştüğünü ya da nerede kaybolduğunu.",
        diagnosticQuestions: [
          "İlk ekran çalışıyor mu?",
          "CTA görülüyor mu?",
          "Mobile deneyim kırılıyor mu?",
          "Kullanıcı nerede çıkıyor?",
        ],
        smallLine: [{ text: "Landing page," }, { text: "kampanyanın dışında değil." }],
        variant: "journey",
      },
      {
        number: "04",
        name: "CONVERSION",
        mainQuestion: ["İlgi,", "aksiyona dönüşüyor mu?"],
        signals: [
          "Conversion Rate",
          "CPA",
          "CAC",
          "Lead Completion",
          "Checkout Completion",
          "Purchase",
          "Booking",
          "Qualified Lead",
        ],
        meaning: "Yolculuğun gerçekten iş sonucuna dönüşüp dönüşmediğini.",
        diagnosticQuestions: ["Kaç kişi tamamladı?", "Kaça mal oldu?", "Hangi kaynak daha kaliteli?", "Nerede friction var?"],
        smallLine: [{ text: "Tıklama bir sonuç değil." }, { text: "Bir geçiş noktası." }],
        variant: "metric",
        dark: true,
      },
      {
        number: "05",
        name: "CUSTOMER",
        mainQuestion: ["Peki gelen kişi", "doğru kişi mi?"],
        signals: ["Lead Quality", "Repeat Purchase", "Retention", "CRM Stage", "Customer Value", "AOV", "Reactivation", "Lifecycle"],
        meaning: "Acquisition'ın yalnızca ucuz olup olmadığını değil, iş için değer üretip üretmediğini.",
        diagnosticQuestions: [
          "Lead satışa dönüyor mu?",
          "Müşteri geri geliyor mu?",
          "Hangi kaynak daha kaliteli?",
          "CRM'de ne oluyor?",
        ],
        smallLine: [{ text: "En ucuz müşteri," }, { text: "her zaman en iyi müşteri değildir." }],
        variant: "lifecycle",
      },
    ],
    loopNote: "Bir sonraki media kararına döner.",
    keyStatement: [
      { text: "Biz reklamı" },
      { text: "optimize etmiyoruz." },
      { text: "Yolculuğu", accent: true },
      { text: "optimize ediyoruz.", accent: true },
    ],
    ending: [{ text: "Rakamları toplamıyoruz." }, { text: "Aralarındaki ilişkiyi arıyoruz.", accent: true }],
    endingNote: "Çünkü karar, tek bir dashboard'dan çıkmıyor.",
  },
  approach: {
    label: "YAKLAŞIMIMIZI İNCELE",
    topics: [
      { number: "01", label: "TEŞHİS" },
      { number: "02", label: "SİSTEM" },
      { number: "03", label: "İLK 30 GÜN" },
      { number: "04", label: "NEYE BAKIYORUZ?" },
    ],
  },
  kite: {
    folioNumber: "012",
    microLabel: "KITE HAKKINDA",
    primaryStatement: ["İSTANBUL'DAN BALI'YE.", "AYNI YÖNDE."],
    citiesLabel: "ISTANBUL × BALI",
    aboutCopy: [
      "KITE, strateji, creative, media, web ve data arasındaki boşluklarla ilgilenen bir growth ajansı.",
      "Çünkü çoğu zaman problem parçaların kendisinde değil, birbirleriyle nasıl çalıştıklarında.",
    ],
    cities: [
      {
        name: "ISTANBUL",
        descriptors: ["Strateji.", "Tempo.", "Kültür.", "Hareket."],
        coordinates: "41.0082° N / 28.9784° E",
      },
      {
        name: "BALI",
        descriptors: ["Perspektif.", "Yaratıcılık.", "Alan.", "Özgürlük."],
        coordinates: "8.3405° S / 115.0920° E",
      },
    ],
    microAnnotation: "UTC+3 / UTC+8",
    nextSectionHint: {
      number: "007",
      title: "LET'S WORK TOGETHER",
    },
  },
  thinking: {
    folioNumber: "013",
    title: "THINKING",
    mainStatement: ["BAZEN İŞ YAPMADAN ÖNCE,", "İŞ HAKKINDA DÜŞÜNÜYORUZ."],
    topics: [
      {
        number: "01",
        category: "CREATIVE",
        statement: ["GÜZEL CREATIVE İLE ÇALIŞAN CREATIVE", "AYNI ŞEY DEĞİL."],
      },
      {
        number: "02",
        category: "PERFORMANCE",
        statement: ["ROAS BAZEN CEVAPTAN", "ÇOK SORUDUR."],
      },
      {
        number: "03",
        category: "GROWTH",
        statement: ["HER ŞEYİ OPTİMİZE ETMEK,", "HER ZAMAN BÜYÜMEK DEĞİLDİR."],
      },
    ],
    nextSectionHint: {
      number: "007",
      title: "LET'S WORK TOGETHER",
    },
  },
  finalCta: {
    folioNumber: "007",
    mainStatement: ["BİRLİKTE", "İYİ ŞEYLER", "YAPALIM."],
    supportingCopy: "Markanızı, hedefinizi ve nerede takıldığınızı anlatın. Gerisini birlikte çözeriz.",
    form: {
      nameLabel: "Ad Soyad",
      emailLabel: "E-posta",
      phoneLabel: "Telefon",
      companyLabel: "Marka / Şirket",
      needsLabel: "Neye ihtiyacınız var?",
      needsOptions: [
        "STRATEGY & GROWTH",
        "PERFORMANCE MEDIA",
        "CREATIVE & CONTENT",
        "WEB & CONVERSION",
        "DATA / CRM",
        "EMİN DEĞİLİM",
      ],
      messageLabel: "Projenizi kısaca anlatın",
      submitLabel: "PROJEYİ GÖNDER",
      submittingLabel: "GÖNDERİLİYOR...",
      note: "Genelde 1 iş günü içinde dönüş yapıyoruz.",
      successMessage: "Mesajınız alındı. En kısa sürede dönüş yapacağız.",
      errorMessage: "Bir şeyler ters gitti. Lütfen tekrar deneyin.",
    },
  },
  footer: {
    copyright: "© KITE GROWTH AGENCY",
    privacy: "Privacy",
    terms: "Terms",
  },
  designSystemPreview: {
    eyebrow: "DAHİLİ ÖNİZLEME",
    title: "Tasarım Sistemi",
    subtitle:
      "Bu sayfa ana sayfa değildir. Tipografi, renk, bileşen ve düzen temellerinin editoryal bir dökümüdür.",
    statusNote: "Ana sayfa henüz oluşturulmadı — bölümler tek tek onaylanacaktır.",
    sectionLabels: {
      typography: "TİPOGRAFİ",
      color: "RENK SİSTEMİ",
      texture: "KAĞIT DOKUSU",
      buttons: "BUTONLAR",
      links: "METİN BAĞLANTILARI",
      numbering: "BÖLÜM NUMARALANDIRMA",
      borders: "ÇERÇEVE DİLİ",
      spacing: "BOŞLUK SİSTEMİ",
      grid: "IZGARA DAVRANIŞI",
    },
    displaySampleHeadline: "TİPOGRAFİ BİR YAPIDIR.",
    displaySampleSubline: "BU BİR GÖSTERİM METNİDİR.",
    bodySampleParagraph:
      "Bu bir gövde metni örneğidir. Amaç, arayüz tipografisinin okunabilirliğini ve editoryal ritmini farklı ölçeklerde göstermektir.",
    primaryCtaLabel: "PRIMARY CTA",
    secondaryCtaLabel: "SECONDARY CTA",
  },
};

export default tr;
