import type { SiteDictionary } from "@/lib/i18n/types";

const en: SiteDictionary = {
  meta: {
    title: "KITE Growth Agency — Design System",
    description:
      "Internal preview of the editorial design system built for KITE Growth Agency.",
  },
  brand: {
    name: "KITE",
    agencyType: "GROWTH AGENCY",
    statement: "We're the wind behind your brand.",
    location: "ISTANBUL & BALI BASED",
    globalNote: "WORKING GLOBALLY",
  },
  ui: {
    skipToContent: "Skip to content",
    languageSwitcherLabel: "Switch language",
    back: "Back",
    closeLabel: "Close",
  },
  header: {
    locationShort: "ISTANBUL & BALI",
    nav: {
      work: "WORK",
      services: "SERVICES",
      about: "ABOUT",
      thinking: "THINKING",
      contact: "CONTACT",
    },
    cta: "START A PROJECT",
    mobileMenu: {
      openLabel: "Menu",
      closeLabel: "Close",
      ariaLabel: "Main menu",
      menuEyebrow: "MENU",
      nav: {
        work: "WORK",
        services: "SERVICES",
        about: "ABOUT",
        thinking: "THINKING",
        contact: "CONTACT",
      },
      social: {
        instagram: "Instagram",
        linkedin: "LinkedIn",
        behance: "Behance",
        email: "Email",
      },
    },
  },
  hero: {
    indexLabel: "HERO",
    headline: [
      [{ text: "GOOD BRANDS" }],
      [{ text: "DON'T NEED" }],
      [{ text: "MORE NOISE." }],
    ],
    secondaryStatement: [{ text: "THEY NEED" }, { text: "DIRECTION.", accent: true }],
    supportingCopy: [
      "We're a creative growth agency building brands that move, connect and grow.",
      "—",
      "Strategy. Creativity. Technology. Growth.",
    ],
    primaryCta: "LET'S TALK",
    secondaryCta: "SEE OUR WORK",
    capabilities: ["CREATIVE", "MEDIA", "WEB", "AI", "CRM"],
    showreelLabel: "PLAY SHOWREEL",
    scrollLabel: "SCROLL TO EXPLORE",
    stampLines: ["MOVE BRANDS", "FORWARD"],
    nextSectionHint: {
      number: "002",
      title: "SELECTED WORK",
      viewAllLabel: "VIEW ALL PROJECTS",
    },
  },
  work: {
    indexLabel: "SELECTED WORK",
    supportingLines: ["DIFFERENT INDUSTRIES.", "ONE QUESTION:", "THE RIGHT DIRECTION."],
    featuredLabel: "FEATURED",
    statusOngoing: "ONGOING",
    nextSectionHint: {
      number: "003",
      title: "WHAT WE DO",
    },
    projects: [
      {
        number: "01",
        name: "DESETOUR",
        services: ["Website", "Ads", "Social Media", "CRM"],
      },
      {
        number: "02",
        name: "ECRU ATELIER",
        services: ["Ads", "Social Media"],
      },
      {
        number: "03",
        name: "TITOCAR",
        services: ["Ad Management"],
      },
      {
        number: "04",
        name: "LYXASKIN",
        services: ["Social Media", "Ads"],
      },
      {
        number: "05",
        name: "PETCANVAS",
        services: ["Ad Management"],
      },
    ],
    cta: {
      number: "06",
      headline: "ONE BRAND MISSING.",
      label: "LET'S MEET.",
    },
  },
  capabilities: {
    indexLabel: "WHAT WE DO",
    introStatement: "We don't treat growth as a single service.",
    introSupport:
      "From what your brand says, to who your ads reach, to which page users land on, to what happens next in your CRM — we take on the whole journey together.",
    systemLine: ["STRATEGY", "CREATIVE", "MEDIA", "WEB", "DATA", "CRM"],
    items: [
      {
        number: "01",
        title: "STRATEGY & GROWTH",
        statement: [
          { text: "We decide what to say, who to say it to, and " },
          { text: "what to test at every stage.", accent: true },
        ],
        groups: [
          {
            items: [
              "Growth Audit",
              "Market & Competitor Analysis",
              "Audience Research",
              "Positioning",
              "Messaging",
              "Offer Strategy",
              "Campaign Planning",
              "Channel Strategy",
              "Testing Roadmap",
            ],
          },
        ],
        secondary: {
          label: "OUTPUTS",
          items: ["Growth Roadmap", "Campaign Architecture", "Messaging Framework", "Test Plan", "Channel Plan"],
        },
      },
      {
        number: "02",
        title: "PERFORMANCE MEDIA",
        statement: [
          { text: "Not spending the budget — directing it to " },
          { text: "the right place.", accent: true },
        ],
        supportingCopy: "We evaluate every campaign as part of the funnel, not on its own.",
        groups: [
          {
            items: [
              "Meta Ads",
              "Google Ads",
              "TikTok Ads",
              "YouTube",
              "Search",
              "Performance Max",
              "Retargeting",
              "Lookalike Audiences",
              "Audience Testing",
              "Creative Testing",
              "Budget Optimisation",
              "Campaign Scaling",
            ],
          },
        ],
        secondary: {
          label: "WHAT WE MEASURE",
          items: ["CPA", "CAC", "ROAS", "CTR", "Conversion Rate", "Creative Performance", "Audience Saturation"],
        },
      },
      {
        number: "03",
        title: "CREATIVE & CONTENT",
        statement: [
          { text: "Good creative doesn't just look good. " },
          { text: "It makes people act.", accent: true },
        ],
        groups: [
          {
            label: "BRAND CONTENT",
            items: [
              "Social Content",
              "Campaign Concepts",
              "Editorial Content",
              "Product Storytelling",
              "Reels",
              "Short Form Video",
              "Motion Design",
            ],
          },
          {
            label: "PERFORMANCE CREATIVE",
            items: [
              "Static Ads",
              "Motion Ads",
              "Video Ads",
              "Creative Variations",
              "Multiple Hooks",
              "Multiple Angles",
              "Retargeting Creative",
              "UGC Concepts",
            ],
          },
        ],
        secondary: {
          label: "AI-ASSISTED PRODUCTION",
          items: ["AI Imagery", "AI Video", "Rapid Prototyping", "Creative Variation", "Concept Development"],
          note: "AI scales production capacity. The idea still makes the decision.",
        },
      },
      {
        number: "04",
        title: "WEB & CONVERSION",
        statement: [
          { text: "What happens after the click is " },
          { text: "still part of the ad.", accent: true },
        ],
        supportingCopy: "We turn the attention an ad earns into conversion through a deliberately designed user journey.",
        groups: [
          {
            items: [
              "Website",
              "Landing Page",
              "E-Commerce",
              "Campaign Page",
              "Product Page",
              "UX Architecture",
              "Conversion Copy",
              "CTA Hierarchy",
              "Lead Forms",
              "Checkout Flow",
              "CRO",
              "A/B Testing",
              "Responsive Design",
            ],
          },
        ],
      },
      {
        number: "05",
        title: "DATA, CRM & LIFECYCLE",
        statement: [
          { text: "If we can't see what happens after the click, we can't " },
          { text: "grow what happens before it in a healthy way.", accent: true },
        ],
        groups: [
          { label: "MEASUREMENT", items: ["GA4", "Google Tag Manager", "Meta Pixel", "Conversions API", "Event Tracking"] },
          { label: "CRM", items: ["CRM Setup", "Lead Routing", "Customer Segmentation", "CRM Integrations"] },
          { label: "LIFECYCLE", items: ["Email Flows", "Retargeting Audiences", "Lead Nurturing", "Customer Reactivation"] },
          {
            label: "REPORTING",
            items: ["Performance Dashboards", "Channel Reporting", "Funnel Visibility", "Campaign Learning"],
          },
        ],
      },
    ],
  },
  investigation: {
    folioNumber: "004",
    title: "INVESTIGATION",
    introLines: ["WHEN WE MEET A BRAND FOR THE FIRST TIME,", "WE ASK THESE 13 QUESTIONS FIRST."],
    investigationDetails: ["STATUS: UNDER REVIEW", "EVIDENCE: DATA", "NOTE: A FEELING ISN'T ENOUGH"],
    questions: [
      {
        number: "01",
        question: "WHO?",
        answerLines: [[{ text: "Who is the brand?" }], [{ text: "Really, who?" }]],
        label: "BRAND / POSITIONING",
      },
      {
        number: "02",
        question: "TO WHOM?",
        answerLines: [
          [{ text: "Who are we talking to?" }],
          [{ text: "'Everyone'", accent: true }, { text: " doesn't count." }],
        ],
        label: "AUDIENCE",
      },
      {
        number: "03",
        question: "WHAT?",
        answerLines: [[{ text: "What are we actually selling?" }], [{ text: "The product, or the idea?" }]],
        label: "OFFER",
      },
      {
        number: "04",
        question: "WHY?",
        answerLines: [
          [{ text: "Why buy from you?" }],
          [{ text: "'We're better quality'", accent: true }, { text: " doesn't count." }],
        ],
        label: "VALUE PROPOSITION",
      },
      {
        number: "05",
        question: "WHERE?",
        answerLines: [[{ text: "Where do we show up?" }], [{ text: "Being everywhere isn't a strategy." }]],
        label: "CHANNEL",
      },
      {
        number: "06",
        question: "WITH WHAT?",
        answerLines: [
          [{ text: "With which creative?" }],
          [{ text: "Not the pretty one — " }, { text: "the one that works.", accent: true }],
        ],
        label: "CREATIVE",
      },
      {
        number: "07",
        question: "WHEN?",
        answerLines: [[{ text: "When do we show up?" }], [{ text: "Showing up constantly isn't an answer." }]],
        label: "TIMING / FREQUENCY",
      },
      {
        number: "08",
        question: "AT WHAT COST?",
        answerLines: [
          [{ text: "What does one customer cost us?" }],
          [{ text: "'The budget's going'", accent: true }, { text: " isn't a metric." }],
        ],
        label: "CAC / CPA",
      },
      {
        number: "09",
        question: "TO WHERE?",
        answerLines: [[{ text: "Where does the click go?" }], [{ text: "And why does it stay there?" }]],
        label: "LANDING / CONVERSION",
      },
      {
        number: "10",
        question: "WHERE DID IT BREAK?",
        answerLines: [[{ text: "Where do they give up?" }], [{ text: "Somewhere, it always breaks." }]],
        label: "FUNNEL",
      },
      {
        number: "11",
        question: "WHO CAME BACK?",
        answerLines: [[{ text: "Who came back?" }], [{ text: "The first sale doesn't close the file." }]],
        label: "RETENTION / CRM",
      },
      {
        number: "12",
        question: "WHAT ACTUALLY WORKED?",
        answerLines: [[{ text: "What actually worked?" }], [{ text: "Not what it felt like.", accent: true }]],
        label: "PERFORMANCE / DATA",
      },
      {
        number: "13",
        question: "NOW WHAT?",
        answerLines: [
          [{ text: "What do we change next?" }],
          [{ text: "'A bit more budget'", accent: true }, { text: " isn't the only answer." }],
        ],
        label: "OPTIMISATION",
      },
    ],
    ending: [{ text: "If we can answer 4 of the 13," }, { text: "that's half the job done.", accent: true }],
    endingNote: "Data handles the rest.",
  },
  diagnosis: {
    folioNumber: "005",
    title: "DIAGNOSIS",
    introLines: ["BRANDS USUALLY COME TO US", "WITH ONE OF THESE SIX SENTENCES."],
    introSupport:
      "When performance drops, the first reflex is usually to change the ad. But the problem can be anywhere else in the journey — from creative to the website, from the offer to tracking.",
    problems: [
      {
        number: "01",
        label: "SYMPTOM",
        statement: [[{ text: "We're spending more." }], [{ text: "Same result.", accent: true }]],
        secondaryLine: "If the problem doesn't go away when the budget goes up, the budget probably isn't the problem.",
        causes: ["Creative Fatigue", "Audience Saturation", "Offer", "Landing Page", "Tracking", "Campaign Structure"],
        conclusion: [[{ text: "We don't just look at Ads Manager." }]],
      },
      {
        number: "02",
        statement: [[{ text: "The content looks great." }], [{ text: "It just doesn't sell.", accent: true }]],
        secondaryLine: "Looking good is one thing. Moving someone to the next step is another.",
        causes: ["Weak Hook", "Wrong Message", "No Clear CTA", "Format", "Creative Fatigue", "Offer Mismatch"],
        stages: ["Attention", "Interest", "Action"],
        conclusion: [[{ text: "A good post isn't a business model on its own." }]],
      },
      {
        number: "03",
        label: "LOSS POINT",
        statement: [[{ text: "There's traffic." }], [{ text: "No conversion.", accent: true }]],
        secondaryLine: "Clicks happen. Everything after that gets lost.",
        causes: ["Landing Page", "Mobile UX", "Page Speed", "CTA", "Form Friction", "Checkout", "Conversion Copy"],
        conclusion: [[{ text: "There's traffic, but the journey after it might not be working." }]],
      },
      {
        number: "04",
        statement: [[{ text: "On every channel," }], [{ text: "we're a different brand.", accent: true }]],
        secondaryLine: "Instagram says one thing. Google says another. The website says another. Sales says another.",
        causes: [
          "Positioning",
          "Messaging",
          "Offer Hierarchy",
          "Campaign Messaging",
          "Content Direction",
          "Sales Narrative",
        ],
        conclusion: [
          [{ text: "A good brand doesn't repeat the same sentence everywhere." }],
          [{ text: "It carries the same idea.", accent: true }],
        ],
      },
      {
        number: "05",
        label: "SIGNAL",
        statement: [[{ text: "Too much data." }], [{ text: "No answer.", accent: true }]],
        secondaryLine: "Four dashboards open. Still no idea what to do next.",
        causes: ["Meta", "Google", "GA4", "CRM", "Website", "E Commerce"],
        diagnosticQuestions: [
          "What's working?",
          "Why is it working?",
          "Where's the drop-off?",
          "What do we change next?",
        ],
        conclusion: [
          [{ text: "A dashboard isn't an answer." }],
          [{ text: "If we can't make a decision, data is just noise." }],
        ],
      },
      {
        number: "06",
        statement: [[{ text: "Everything is being done." }], [{ text: "None of it is connected." }]],
        supportingLines: [
          "There are ads.",
          "There's social media.",
          "There's a website.",
          "There's a CRM.",
          "None of them talk to each other.",
        ],
        systemLine: ["Creative", "Media", "Web", "Data", "CRM"],
        conclusion: [[{ text: "This is exactly where Kite steps in." }]],
      },
    ],
  },
  system: {
    folioNumber: "006",
    title: "SYSTEM",
    introLines: ["GROWTH", "DOESN'T HAPPEN", "IN A SINGLE CHANNEL."],
    introSupport:
      "When creative, media, web, data and CRM run independently, it gets hard to see where growth starts and where it gets lost. We run these parts inside one system.",
    canvasDetails: ["SYSTEM / 01–06", "LOOP: CONTINUOUS"],
    stages: [
      {
        number: "01",
        name: "UNDERSTAND",
        term: "INSIGHT",
        question: "What's happening?",
        details: ["Market", "Audience", "Competitors", "Past performance", "Customer journey", "Existing data"],
        outcome: "We see the full picture first.",
      },
      {
        number: "02",
        name: "POSITION",
        term: "DIRECTION",
        question: "What will we say?",
        details: ["Positioning", "Offer", "Messaging", "Campaign angle", "Channel role", "Testing priorities"],
        outcome: "We set the direction.",
      },
      {
        number: "03",
        name: "CREATE",
        term: "CREATIVE",
        question: "Why would someone stop and look?",
        details: ["Campaign concept", "Static creative", "Video", "Content", "Hooks", "Angles", "Variations"],
        outcome: "We make the idea visible.",
      },
      {
        number: "04",
        name: "DISTRIBUTE",
        term: "MEDIA",
        question: "To whom, where, how much?",
        details: ["Meta", "Google", "TikTok", "YouTube", "Prospecting", "Retargeting", "Budget allocation"],
        outcome: "We get the right message to the right place.",
      },
      {
        number: "05",
        name: "CONVERT",
        term: "CONVERSION",
        question: "They clicked. Now what?",
        details: ["Website", "Landing Page", "E Commerce", "Form", "Checkout", "CRM", "Lead flow"],
        outcome: "We turn interest into action.",
      },
      {
        number: "06",
        name: "LEARN",
        term: "DATA",
        question: "So what happened?",
        details: ["Campaign data", "Creative data", "Website behaviour", "Conversion data", "CRM", "Customer quality"],
        outcome: "We turn the result into the next decision.",
      },
    ],
    loopNote: "Loops back to 01.",
    closing: [
      { text: "Every campaign," },
      { text: "should teach the next one" },
      { text: "something.", accent: true },
    ],
    closingNote: "Otherwise, we're just repeating the same thing.",
  },
  firstMonth: {
    folioNumber: "007",
    title: "THE FIRST 30 DAYS",
    introLines: [
      [{ text: "Our first job" }],
      [{ text: "isn't to produce something." }],
      [{ text: "It's understanding", accent: true }],
      [{ text: "what needs to change." }],
    ],
    introSupport:
      "A new creative, campaign or landing page is sometimes genuinely necessary. Sometimes it isn't. In the early days, the goal isn't to do more — it's to find the right thing.",
    phases: [
      {
        number: "01",
        timeLabel: "DAY 01–07",
        title: "We map the big picture.",
        statement: "First we look at what's already in place. Because we can't decide what to change without knowing what's working.",
        areasLabel: "WHAT WE LOOK AT",
        areas: [
          "Business Goals",
          "Existing Campaigns",
          "Creative Library",
          "Website",
          "Landing Pages",
          "Analytics",
          "CRM",
          "Tracking",
          "Competitors",
          "Customer Journey",
          "Historical Performance",
        ],
        outputLabel: "FIRST OUTPUT",
        output: "Current state analysis",
        note: "What exists, what doesn't, what's working, what's just sitting there?",
        microLabel: "STATUS: ANALYSIS",
      },
      {
        number: "02",
        timeLabel: "DAY 08–14",
        title: "We find where growth is being lost.",
        statement: "Is the problem in the ad account, the creative, the offer, or the conversion? First we separate these.",
        areasLabel: "DIAGNOSTIC AREAS",
        areas: ["Acquisition", "Creative", "Audience", "Offer", "Conversion", "Tracking", "Messaging", "Retention"],
        outputLabel: "OUTPUT",
        output: "Prioritised growth roadmap",
        note: "Not every problem gets solved at once. We touch where it moves the needle most, first.",
      },
      {
        number: "03",
        timeLabel: "DAY 15–30",
        title: "We build the system.",
        statement: "Once the diagnosis is clear, we start producing the necessary pieces and connecting them to each other.",
        areasLabel: "POSSIBLE WORKSTREAMS",
        areas: [
          "Campaign Structure",
          "Creative Production",
          "Landing Page",
          "Tracking",
          "Audience Structure",
          "CRM",
          "Reporting",
          "Conversion Flow",
          "Testing Infrastructure",
        ],
        outputLabel: "OUTPUT",
        output: "Launch-ready setup",
        note: "If a new system is needed, we build it. If it isn't, we don't rebuild it just to look new.",
      },
      {
        number: "04",
        timeLabel: "AFTER DAY 30",
        title: "The loop begins.",
        statement: "What follows isn't a recurring production calendar. It's a learning loop.",
        loopSequence: ["DATA", "HYPOTHESIS", "CREATIVE", "TEST", "RESULT", "NEW DECISION"],
        questions: ["WHAT WORKED?", "WHAT DIDN'T?", "WHY?", "WHAT DO WE TEST NEXT?"],
        microLabel: "SIGNAL",
      },
    ],
    closing: [
      { text: "We don't repeat" },
      { text: "the same thing every month." },
      { text: "Every month we know" },
      { text: "more than we did before.", accent: true },
    ],
  },
  caseStudies: {
    folioNumber: "008",
    title: "THE WORK BEHIND THE WORK",
    introLines: [
      [{ text: "Showing the work" }],
      [{ text: "that looks good is easy." }],
      [{ text: "What matters is" }],
      [{ text: "what you built behind it.", accent: true }],
    ],
    introSupport:
      "On some projects we touch creative. On others, media. On others, the whole journey from the website to CRM. What we're showing here isn't the visible side of the work — it's the system behind it.",
    scopeLabel: "SCOPE",
    contextLabel: "CONTEXT",
    workLabel: "WHAT KITE TOUCHED",
    systemLabel: "SYSTEM",
    ongoingLabel: "ONGOING",
    cases: [
      {
        number: "01",
        client: "DESETOUR",
        category: "TRAVEL / EXPERIENCES",
        statement: [{ text: "Not a tour website." }, { text: "A whole digital journey.", accent: true }],
        context:
          "DeseTour builds curated private Istanbul experiences. Kite's role spans multiple points of the customer journey rather than a single marketing channel.",
        scope: ["Website", "Paid Media", "Social Media", "CRM Systems"],
        workItems: [
          "Digital experience",
          "Tour presentation",
          "Booking journey",
          "Paid media infrastructure",
          "Social content system",
          "Lead capture",
          "CRM flow",
        ],
        systemSequence: ["CONTENT / ADS", "WEBSITE", "BOOKING", "CRM"],
        systemJoiner: "arrow",
        smallLine: [{ text: "From the ad to the booking." }, { text: "From the booking to the CRM." }],
        imageAlign: "left",
      },
      {
        number: "02",
        client: "ECRU ATELIER",
        category: "JEWELRY / E COMMERCE",
        statement: [{ text: "Looking premium isn't enough." }, { text: "The creative has to work.", accent: true }],
        context:
          "Ecru Atelier is a premium jewelry brand. The work combines brand consistency with the constant creative requirements of paid social.",
        scope: ["Social Media Management", "Creative", "Paid Media"],
        workItems: [
          "Social content",
          "Campaign communication",
          "Product storytelling",
          "Performance creative",
          "Creative variations",
          "Meta advertising",
          "Campaign optimisation",
        ],
        systemSequence: ["BRAND", "CREATIVE", "MEDIA"],
        systemJoiner: "plus",
        smallLine: [{ text: "Brand and performance" }, { text: "meet in the same creative.", accent: true }],
        dark: true,
        imageAlign: "right",
      },
      {
        number: "03",
        client: "LYXASKIN",
        category: "SKINCARE",
        statement: [{ text: "We produce content." }, { text: "Then we look at what it does.", accent: true }],
        context: "Lyxa Skin is an ongoing social and performance partnership.",
        scope: ["Social Media Management", "Creative", "Paid Media"],
        workItems: [
          "Product communication",
          "Social content",
          "Creative direction",
          "Performance creative",
          "Paid campaigns",
          "Creative iteration",
        ],
        systemSequence: ["CREATE", "PUBLISH", "MEASURE", "LEARN", "CREATE AGAIN"],
        systemJoiner: "arrow",
        systemLoop: true,
        closingLine: [{ text: "Creative isn't a deliverable." }, { text: "It's a loop.", accent: true }],
        ongoing: true,
        imageAlign: "left",
      },
    ],
    closing: [
      { text: "Every project's scope is different." },
      { text: "The logic is the same.", accent: true },
      { text: "Find the problem." },
      { text: "Connect the right pieces." },
      { text: "Learn." },
    ],
  },
  collaboration: {
    folioNumber: "009",
    title: "HOW YOU CAN WORK WITH US",
    introLines: [
      [{ text: "Every brand" }],
      [{ text: "has different needs." }],
      [{ text: "The way we work" }],
      [{ text: "doesn't have to be the same." }],
    ],
    introSupport:
      "Sometimes we work like the brand's external growth team. Sometimes we just build the creative system. Sometimes we step in for a single launch or digital build.",
    priorityLabel: "MOST COMPREHENSIVE MODEL",
    bestForLabel: "WHO IT'S FOR",
    scopeLabel: "SCOPE",
    workingModelLabel: "WORKING MODEL",
    models: [
      {
        number: "01",
        title: "GROWTH PARTNERSHIP",
        description: "We work like the brand's external growth team.",
        bestFor: [
          "Brands with active ad spend",
          "Running acquisition continuously",
          "With ongoing creative needs",
          "Who want to regularly optimise performance",
        ],
        scope: ["Strategy", "Paid Media", "Creative", "Analytics", "CRO", "Landing Page", "Reporting", "Testing"],
        workingModel: "ONGOING RETAINER",
        smallLine: [{ text: "Not a campaign." }, { text: "A system that keeps running.", accent: true }],
        priority: true,
      },
      {
        number: "02",
        title: "CREATIVE PERFORMANCE",
        description: "If media is working but creative can't keep up, the problem might be in the production system before the budget.",
        bestFor: [
          "Brands with their own media team",
          "Running active ads on Meta / TikTok",
          "Experiencing creative fatigue",
          "Needing more variation and testing",
        ],
        scope: [
          "Creative Strategy",
          "Static Ads",
          "Motion",
          "Video",
          "Hooks",
          "Angles",
          "Creative Variations",
          "Testing Plan",
          "Performance Learning",
        ],
        workingModel: "ONGOING / PERIODIC",
        smallLine: [{ text: "Not more creative." }, { text: "Creative that learns more.", accent: true }],
        dark: true,
      },
      {
        number: "03",
        title: "DIGITAL BUILD",
        description: "If a new digital experience is needed, we build the necessary infrastructure within a single project.",
        bestFor: [
          "A new website",
          "Landing page",
          "E Commerce",
          "CRM",
          "Analytics",
          "Tracking",
          "Brands needing conversion infrastructure",
        ],
        scope: [
          "Website",
          "Landing Page",
          "E Commerce",
          "UX",
          "Conversion Copy",
          "GA4",
          "GTM",
          "Pixel / CAPI",
          "CRM Setup",
          "Lead Flow",
        ],
        workingModel: "PROJECT BASED",
        smallLine: [{ text: "Not to look new." }, { text: "To work better.", accent: true }],
      },
      {
        number: "04",
        title: "LAUNCH",
        description:
          "For a new brand, product or market, we bring together the pieces that need to move in the same direction in a short amount of time.",
        bestFor: ["A new brand", "A new product", "A new service", "A new market", "A new campaign period"],
        scope: ["Strategy", "Positioning", "Messaging", "Creative", "Landing Page", "Paid Launch", "Tracking", "Reporting"],
        workingModel: "SPRINT / PROJECT",
        smallLine: [{ text: "Going live is easy." }, { text: "Being ready is harder.", accent: true }],
      },
    ],
    ctaHeadline: [
      { text: "If you're not sure" },
      { text: "which model fits," },
      { text: "that's fine.", accent: true },
    ],
    ctaSupport: "Tell us what you need. Let's figure out together where to start.",
    ctaLabel: "TELL US ABOUT YOUR PROJECT",
  },
  principles: {
    folioNumber: "010",
    title: "WE BELIEVE A FEW THINGS",
    introLines: ["BEFORE WE DO", "CERTAIN THINGS,", "WE ALREADY HAVE", "AN OPINION ABOUT THEM."],
    introSupport:
      "From creative to media, from the website to data — there are a few simple principles behind everything we do.",
    items: [
      {
        number: "01",
        statement: [
          [{ text: "Creative" }],
          [{ text: "isn't the decoration on the ad." }],
          [{ text: "It's the performance itself.", accent: true }],
        ],
        supportingCopy: "However well media is managed, it can't scale a creative nobody stops to look at.",
        technicalLabel: "CREATIVE / PERFORMANCE",
        variant: "C",
        dark: true,
      },
      {
        number: "02",
        statement: [[{ text: "More traffic" }], [{ text: "doesn't save" }], [{ text: "a bad journey." }]],
        supportingCopy:
          "The ad brings the click. The website, landing page, offer and conversion experience decide what happens after.",
        technicalLabel: "TRAFFIC / CONVERSION",
        tinyLine: ["A click isn't success. It's the start."],
        variant: "A",
      },
      {
        number: "03",
        statement: [[{ text: "What we can't measure," }], [{ text: "we can't grow" }], [{ text: "in a healthy way." }]],
        supportingCopy: "Data isn't there to fill a dashboard. It's there to make the next decision better.",
        technicalLabel: "DATA / DECISION",
        tinyLine: ["There can be a lot of numbers.", "There can still be few answers."],
        variant: "B",
      },
      {
        number: "04",
        statement: [
          [{ text: "AI should let us" }],
          [{ text: "produce more." }],
          [{ text: "Not produce more average work.", accent: true }],
        ],
        supportingCopy:
          "AI grows our capacity for ideas, variation and production. Creative judgement still decides how much of it ships.",
        technicalLabel: "AI / PRODUCTION",
        variant: "C",
        dark: true,
      },
      {
        number: "05",
        statement: [[{ text: "Every campaign" }], [{ text: "should teach" }], [{ text: "the next one something." }]],
        supportingCopy: "If we tested, got a result, and did the same thing again, we've missed half the learning loop.",
        technicalLabel: "TEST / LEARN / ITERATE",
        tinyLine: ["What happened?", "Why did it happen?", "What are we changing now?"],
        variant: "A",
      },
      {
        number: "06",
        statement: [[{ text: "Brand and performance" }], [{ text: "aren't competing with each other." }]],
        supportingCopy:
          "We don't have to choose between protecting the brand and getting results. Good creative can carry both at once.",
        technicalLabel: "BRAND / PERFORMANCE",
        variant: "B",
      },
      {
        number: "07",
        statement: [[{ text: "More channels" }], [{ text: "isn't always" }], [{ text: "more growth." }]],
        supportingCopy: "Knowing which channel actually works is worth more than being everywhere.",
        technicalLabel: "CHANNEL / FOCUS",
        tinyLine: ["Spreading thin is also a media plan.", "Just not a good one."],
        variant: "A",
      },
      {
        number: "08",
        statement: [[{ text: "We don't have to" }], [{ text: "rebuild everything." }]],
        supportingCopy:
          "Sometimes the problem isn't the whole system — it's one connection point. Keeping what works and changing what doesn't is also a strategy.",
        technicalLabel: "DIAGNOSE / PRIORITISE",
        tinyLine: ["New isn't always better."],
        variant: "B",
      },
    ],
    closing: [
      [{ text: "For us, growth isn't" }],
      [{ text: "doing more things." }],
      [{ text: "It's making the right things" }],
      [{ text: "work better", accent: true }],
      [{ text: "together." }],
    ],
  },
  measurement: {
    folioNumber: "011",
    title: "WHAT WE LOOK AT",
    introLines: ["A SINGLE METRIC", "NEVER TELLS", "THE WHOLE STORY."],
    introSupport:
      "ROAS can drop because the creative is fatigued. Conversion can drop because the landing page isn't working. CAC can go up while the quality of the customers coming in goes up too. That's why we look at how the numbers relate to each other, not at each one alone.",
    layers: [
      {
        number: "01",
        name: "MEDIA",
        mainQuestion: ["Are we reaching", "the right person?"],
        signals: ["CPM", "CTR", "CPC", "Frequency", "Reach", "Audience Saturation", "Spend Distribution"],
        meaning: "The cost of distribution, and how the message performs on first contact.",
        diagnosticQuestions: [
          "Is CTR dropping?",
          "Is frequency climbing?",
          "Is the audience fatigued?",
          "Is the budget going to the right campaign?",
        ],
        smallLine: [{ text: "Expensive traffic isn't" }, { text: "always bad traffic." }],
        variant: "grid",
      },
      {
        number: "02",
        name: "CREATIVE",
        mainQuestion: ["Why does someone", "stop and look?"],
        signals: [
          "Hook Rate",
          "Hold Rate",
          "CTR",
          "Creative Fatigue",
          "Winning Angles",
          "Format Performance",
          "Message Performance",
        ],
        meaning: "Which ideas are catching attention, and which ones have stopped working.",
        diagnosticQuestions: ["Which hook held?", "Which angle worked?", "Video or static?", "When did the creative get fatigued?"],
        smallLine: [{ text: "We don't decide if a creative is good." }, { text: "Behaviour does.", accent: true }],
        variant: "typographic",
      },
      {
        number: "03",
        name: "WEBSITE",
        mainQuestion: ["They clicked.", "Then what?"],
        signals: [
          "Engagement",
          "Bounce",
          "Scroll Depth",
          "Page Speed",
          "CTA Interaction",
          "Form Start",
          "Product View",
          "Checkout Behaviour",
        ],
        meaning: "Where the interest from the ad converts on the page — or where it gets lost.",
        diagnosticQuestions: [
          "Is the first screen working?",
          "Is the CTA visible?",
          "Is the mobile experience breaking?",
          "Where does the user drop off?",
        ],
        smallLine: [{ text: "The landing page isn't" }, { text: "outside the campaign." }],
        variant: "journey",
      },
      {
        number: "04",
        name: "CONVERSION",
        mainQuestion: ["Does interest turn", "into action?"],
        signals: [
          "Conversion Rate",
          "CPA",
          "CAC",
          "Lead Completion",
          "Checkout Completion",
          "Purchase",
          "Booking",
          "Qualified Lead",
        ],
        meaning: "Whether the journey actually turns into a business result.",
        diagnosticQuestions: ["How many completed it?", "What did it cost?", "Which source is higher quality?", "Where's the friction?"],
        smallLine: [{ text: "A click isn't a result." }, { text: "It's a transition point." }],
        variant: "metric",
        dark: true,
      },
      {
        number: "05",
        name: "CUSTOMER",
        mainQuestion: ["So is the person", "who came in the right one?"],
        signals: ["Lead Quality", "Repeat Purchase", "Retention", "CRM Stage", "Customer Value", "AOV", "Reactivation", "Lifecycle"],
        meaning: "Not just whether acquisition is cheap — whether it produces value for the business.",
        diagnosticQuestions: [
          "Does the lead turn into a sale?",
          "Does the customer come back?",
          "Which source is higher quality?",
          "What's happening in the CRM?",
        ],
        smallLine: [{ text: "The cheapest customer" }, { text: "isn't always the best one." }],
        variant: "lifecycle",
      },
    ],
    loopNote: "Feeds back into the next media decision.",
    keyStatement: [
      { text: "We don't optimise" },
      { text: "the ad." },
      { text: "We optimise", accent: true },
      { text: "the journey.", accent: true },
    ],
    ending: [{ text: "We don't add up numbers." }, { text: "We look for the relationship between them.", accent: true }],
    endingNote: "Because the decision doesn't come from a single dashboard.",
  },
  approach: {
    label: "EXPLORE OUR APPROACH",
    topics: [
      { number: "01", label: "DIAGNOSIS" },
      { number: "02", label: "SYSTEM" },
      { number: "03", label: "THE FIRST 30 DAYS" },
      { number: "04", label: "WHAT WE LOOK AT" },
    ],
  },
  kite: {
    folioNumber: "012",
    microLabel: "ABOUT KITE",
    primaryStatement: ["FROM ISTANBUL TO BALI.", "SAME DIRECTION."],
    citiesLabel: "ISTANBUL × BALI",
    aboutCopy: [
      "KITE is a growth agency that cares about the gaps between strategy, creative, media, web and data.",
      "Because the problem is rarely in the parts themselves — it's usually in how they work together.",
    ],
    cities: [
      {
        name: "ISTANBUL",
        descriptors: ["Strategy.", "Tempo.", "Culture.", "Momentum."],
        coordinates: "41.0082° N / 28.9784° E",
      },
      {
        name: "BALI",
        descriptors: ["Perspective.", "Creativity.", "Space.", "Freedom."],
        coordinates: "8.3405° S / 115.0920° E",
      },
    ],
    microAnnotation: "UTC+3 / UTC+8",
    nextSectionHint: {
      number: "007",
      title: "LET'S WORK TOGETHER",
    },
  },
  thinking: {
    folioNumber: "013",
    title: "THINKING",
    mainStatement: ["SOMETIMES, BEFORE WE DO THE WORK,", "WE THINK ABOUT THE WORK."],
    topics: [
      {
        number: "01",
        category: "CREATIVE",
        statement: ["GOOD CREATIVE AND CREATIVE THAT WORKS", "ARE NOT THE SAME THING."],
      },
      {
        number: "02",
        category: "PERFORMANCE",
        statement: ["ROAS IS SOMETIMES MORE OF A QUESTION", "THAN AN ANSWER."],
      },
      {
        number: "03",
        category: "GROWTH",
        statement: ["OPTIMIZING EVERYTHING DOESN'T ALWAYS", "MEAN GROWING."],
      },
    ],
    nextSectionHint: {
      number: "007",
      title: "LET'S WORK TOGETHER",
    },
  },
  finalCta: {
    folioNumber: "007",
    mainStatement: ["LET'S MAKE", "SOMETHING GOOD", "TOGETHER."],
    supportingCopy: "Tell us about your brand, your goal, and where things are getting stuck. We'll figure out the rest together.",
    form: {
      nameLabel: "Name",
      emailLabel: "Email",
      phoneLabel: "Phone",
      companyLabel: "Brand / Company",
      needsLabel: "What do you need?",
      needsOptions: [
        "STRATEGY & GROWTH",
        "PERFORMANCE MEDIA",
        "CREATIVE & CONTENT",
        "WEB & CONVERSION",
        "DATA / CRM",
        "NOT SURE YET",
      ],
      messageLabel: "Tell us briefly about your project",
      submitLabel: "SEND PROJECT",
      submittingLabel: "SENDING...",
      note: "We usually reply within 1 business day.",
      successMessage: "Message received. We'll be in touch shortly.",
      errorMessage: "Something went wrong. Please try again.",
    },
  },
  footer: {
    copyright: "© KITE GROWTH AGENCY",
    privacy: "Privacy",
    terms: "Terms",
  },
  designSystemPreview: {
    eyebrow: "INTERNAL PREVIEW",
    title: "Design System",
    subtitle:
      "This is not the homepage. It's an editorial breakdown of the typography, color, component and layout foundations.",
    statusNote: "The homepage has not been built yet — sections will be approved one at a time.",
    sectionLabels: {
      typography: "TYPOGRAPHY",
      color: "COLOR SYSTEM",
      texture: "PAPER TEXTURE",
      buttons: "BUTTONS",
      links: "TEXT LINKS",
      numbering: "SECTION NUMBERING",
      borders: "BORDER LANGUAGE",
      spacing: "SPACING SYSTEM",
      grid: "GRID BEHAVIOR",
    },
    displaySampleHeadline: "TYPOGRAPHY IS STRUCTURE.",
    displaySampleSubline: "THIS IS A DISPLAY SPECIMEN.",
    bodySampleParagraph:
      "This is a body copy sample. Its purpose is to demonstrate interface typography readability and editorial rhythm across scales.",
    primaryCtaLabel: "PRIMARY CTA",
    secondaryCtaLabel: "SECONDARY CTA",
  },
};

export default en;
